# Generated by Django 4.1.7 on 2023-03-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_typefilm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeFilm',
        ),
    ]
