# Generated by Django 4.1.7 on 2023-03-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_delete_typefilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='srcFilm',
            field=models.TextField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
