# Generated by Django 4.1.7 on 2023-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_film_srcfilm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='film%y/%m/'),
        ),
    ]
