# Generated by Django 4.1.7 on 2023-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_alter_film_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='%y/%m/'),
        ),
    ]
