# Generated by Django 4.1.7 on 2023-03-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_alter_film_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='thumbnail',
        ),
    ]
