# Generated by Django 4.1.7 on 2023-03-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_remove_film_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='static/%y/%m/'),
        ),
    ]
