# Generated by Django 4.1.7 on 2023-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_film_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
