# Generated by Django 4.1.7 on 2023-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='srcFilm',
            field=models.TextField(max_length=500),
        ),
    ]
